### ISSUE TITLE
setup.py error when installing via pip

### ISSUE THREAD

**Issue by Nircek** [AGProjects/python-otr#1]
I'm on Arch Linux and when I try to install python-otr, there's the error.
```
$ pip install python-otr --user
Collecting python-otr
 
 Downloading 
https://files.pythonhosted.org/packages/81/af/171a7c6d88b6a7cefbbac3626c43dd39d92f54fd6ac9b49b0de761ec47b7/python-otr-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yhfh1f0b/python-otr/setup.py", line 55, in <module>
        install_requires=[requirement.translate(None, ' ()') for requirement in requirements]
      File "/tmp/pip-install-yhfh1f0b/python-otr/setup.py", line 55, in <listcomp>
        install_requires=[requirement.translate(None, ' ()') for requirement in requirements]
    TypeError: translate() takes exactly one argument (2 given)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yhfh1f0b/python-otr/
$ pip --version
pip 18.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)
$ python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
```

**Comment by danpascu** [comment]
python 3 is not yet supported

**Comment by md84419** [comment]
Python 3 was released in 2008 - any plans to fix?

**Comment by adigeo** [comment]
You can fetch the Python3 version from here:

darcs@devel.ag-projects.com:repositories/python3-otr

This code was not tested in production.

**Comment by adigeo** [comment]
You need darcs version control tool to feth the achive.
